# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  image: latest

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
  - requirements: requirements_base.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
