dist: xenial
language: python
python:
  - "2.7"

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ppa
    packages:
      - libgdal-dev
      - libhdf5-serial-dev
      - libnetcdf-dev
      - netcdf-bin

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest
