# Config file for automatic testing at travis-ci.org
sudo: required

language: python
python:
  - 2.7

services:
  - docker

before_install:
  - docker build -t threedigrid/test .

script:
  - docker run --rm threedigrid/test pytest --cov=threedigrid
  - docker run --rm threedigrid/test bash -c 'cd /code/docs && sphinx-build -nW -b html -d _build/doctrees . _build/html'
