dist: xenial
language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libhdf5-serial-dev libnetcdf-dev netcdf-bin

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest
