dist: xenial
language: python
python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update -q
  - sudo apt-get install -y libgdal-dev libhdf5-serial-dev libnetcdf-dev netcdf-bin

# addons:
#   apt:
#     packages:
#       - libgdal-dev
#       - libhdf5-serial-dev
#       - libnetcdf-dev
#       - netcdf-bin
#     sources:
#       - sourceline: ppa:ubuntugis/ppa
#     update: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest
