# Config file for automatic testing at travis-ci.org
sudo: required

language: python
python:
  - 2.7

services:
  - docker

before_install:
  - docker build -f Dockerfile_ci -t threedigrid:test .

script:
  # - docker run --rm threedigrid/test /bin/bash -c "source /usr/local/venvs/py36/bin/activate && pytest --cov=threedigrid"
  # - docker run --rm threedigrid/test bash -c 'source /usr/local/venvs/py36/bin/activate && cd /code/docs && sphinx-build -nW -b html -d _build/doctrees . _build/html'

  - docker run --rm threedigrid:test /usr/local/venvs/py27/bin/pytest --cov=threedigrid
  - docker run --rm threedigrid:test bash -c 'source /usr/local/venvs/py27/bin/activate && cd /code/docs && sphinx-build -nW -b html -d _build/doctrees . _build/html'
