dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libhdf5-serial-dev

install:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install -r requirements_geo.txt; fi;
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements_geo27.txt; fi;

before_script:
  - pip install flake8 sphinx==1.8.5

script:
  - pytest
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then flake8; fi;
  - sphinx-build -nW docs docs/_build/html
