dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev libhdf5-serial-dev

install:
  - pip install -r requirements.txt -e .

before_script:
  - pip install flake8 sphinx

script:
  - pytest
  - flake8
  - sphinx-build -nW docs docs/_build/html
