FROM ubuntu:xenial

MAINTAINER lars.claussen <lars.claussen@nelen-schuurmans.nl>

# Change the date to force rebuilding the whole image.
ENV REFRESHED_AT 2018-03-02

# http://click.pocoo.org/5/python3/#python-3-surrogate-handling
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Add deadsnakes PPA for additional Python versions (Python 3.6).
# Add ubuntugis PPA. A recent GDAL version is required by the GPKG driver.
RUN apt-get update && apt-get install -y software-properties-common \
&& add-apt-repository -y ppa:deadsnakes/ppa \
&& add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable \
&& rm -rf /var/lib/apt/lists/*

# System dependencies.
RUN apt-get update && apt-get install -y \
    curl \
    libgdal-dev \
    libhdf5-serial-dev \
    libnetcdf-dev \
    netcdf-bin \
    python2.7-dev \
    python3.5-dev \
    python3.6-dev \
&& rm -rf /var/lib/apt/lists/*

# Avoid issues with upgrading an apt-managed pip.
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python2.7

RUN pip install virtualenv
WORKDIR /code
COPY . /code/

RUN virtualenv venvs/py27 --python=python2.7 && \
  venvs/py27/bin/pip install -r requirements.txt -r requirements_dev.txt -e .

RUN virtualenv venvs/py35 --python=python3.5 && \
  venvs/py35/bin/pip install -r requirements.txt -r requirements_dev.txt -e .

RUN virtualenv venvs/py36 --python=python3.6 && \
  venvs/py36/bin/pip install -r requirements.txt -r requirements_dev.txt -e .
