BYTE_ORDER = '<'
DTYPE_INT = BYTE_ORDER + 'i4'
DTYPE_FLOAT = BYTE_ORDER + 'f8'

DIM_2D_CELL_COORDS = 4
DIM_LINE_ARRAY = 2
DIM_PUMP = 2

# ------------------ NODE TYPES ------------------ #
NODE_TYPE_1D = 1
NODE_TYPE_2D = 2
NODE_TYPE_GROUNDWATER_2D = 3
NODE_TYPE_BOUNDARY_1D = -1
NODE_TYPE_BOUNDARY_2D = -2
NODE_TYPE_BOUNDARY_GROUNDWATER_2D = -3

# ------------------ LINE TYPES ------------------ #

LINE_TYPE = 101
# LINE_TYPE_1D_ISOLATED =
# LINE_TYPE_1D_CONNECTED =
# LINE_TYPE_1D_EMBEDDED =
#
# LINE_TYPE_2D =


TYPE_V2_PIPE = 'v2_pipe'
TYPE_V2_CHANNEL = 'v2_channel'
TYPE_V2_CULVERT = 'v2_culvert'
TYPE_V2_ORIFICE = 'v2_orifice'
TYPE_V2_WEIR = 'v2_weir'
TYPE_V2_MANHOLE = 'v2_manhole'
TYPE_V2_PUMPSTATION = 'v2_pumpstation'
TYPE_V2_LEVEE = 'v2_levee'
TYPE_V2_1D_LATERAL = 'v2_1d_lateral'

TYPE_V2_1D_BOUNDARY_CONDITIONS = 'v2_1d_boundary_conditions'
TYPE_V2_2D_BOUNDARY_CONDITIONS = 'v2_2d_boundary_conditions'
TYPE_V2_CONNECTION_NODES = 'v2_connection_nodes'

TYPE_V2_BREACH = 'v2_breach'
